name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Building the API Docker image
        run: docker build ./api/ --tag ${{ vars.GITHUB_ACTOR }}/snoopy-api:latest
      - name: Build the client Docker image
        run: docker build ./client/ --tag ${{ vars.GITHUB_ACTOR }}/snoopy-client:latest
      - name: Push the Docker images to the ghcr.io registry
        run: |
          docker login ghcr.io -u ${{ vars.GITHUB_ACTOR }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/snoopy-api:latest
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/snoopy-client:latest