name: Prettier Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        working-directory: client
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Test prettier
        working-directory: client
        run: npx prettier . --check